### PR TITLE
Redesign final

### PR DESCRIPTION
**Pull request by matt-auckland**
Implements the redesign as per Carter's design

### CODE REVIEW

**Comment by craigmacgregor** [comment]
This should be pretty much done, pending a couple of guides.

**Comment by craigmacgregor** [comment]
Multiple project detail pages have merge text in them `<<<<<<< HEAD` and it's causing some of the layouts to break

https://deploy-preview-225--navhub.netlify.com/projects/nav-pay/

**Comment by craigmacgregor** [comment]
The percent in the progress bar on the projects page needs more padding

screen shot 2019-02-04 at 11 34 13 am

**Comment by craigmacgregor** [comment]
Hayden's profile image on the heroes page is broken. Need to check that all the heroes have been added.

screen shot 2019-02-04 at 11 36 03 am

**Comment by matt-auckland** [comment]
Fixed: 
- URL redirects (@craigmacgregor can you check if you are happy with these?)
- Hayden's picture
- Percentage padding
- Merge conflict artifacts

To do:
- Unisex icon for NavCoin Heroes? (@kakax114)

**Pull request merged**
