### PR TITLE
Ready for Testing :: Update cms to newer version with upload improvements

### PR DESCRIPTION
**Pull request by ro-savage**
This PR updates the CMS to the lastest build of the Encrypt-S version of Netlify CMS

Additions:
- You can't add an image without a post title (should stop the seperate PR being made)
- You can edit a draft item and add new images
- You can view previously uploaded images in draft mode
- You still CAN NOT update a previously approved PR with new images.

You can try it out at 
Site: https://ro-navhub.netlify.com/
Admin: https://ro-navhub.netlify.com/admin/
Github: https://github.com/ro-savage/nav-community-site/pulls
Previews: You can see them in the github PR checks

If that all works fine you can try make a real new post from
https://deploy-preview-133--navhub.netlify.com/admin/
I think this will work, but I am not certain.

Once you are happy with everything, then this PR can be approved and merged.

### CODE REVIEW

**Comment by ro-savage** [comment]
Are you guys able to review this PR.
@matt-auckland @kakax114 @kierenhyl

**Comment by ro-savage** [comment]
@matt-auckland 
Heres the changes:
https://github.com/Encrypt-S/netlify-cms/commit/892d1e3220525711d3da88963962f3e3e262219b

And the whole repo: https://github.com/Encrypt-S/netlify-cms

**Comment by ro-savage** [comment]
@matt-auckland - ANy thoughts? Can you get @kierenhyl to test as it was done for them.

**Comment by ro-savage** [comment]
@kierenhyl - Yes, no fix for the paragraphs. That isn't to do with the CMS. Its to do with the templates in Hugo and needs to be changed there.

**Comment by ro-savage** [comment]
@kierenhyl - Can I get an approval from you.

**Comment by matt-auckland** [comment]
Finally got it in 😉 @ro-savage

**Pull request merged**
