### PR TITLE
Navcoin m8

### PR DESCRIPTION
**Pull request by IfaqYurmama**
Adds a project page for the NavCoin m8

### CODE REVIEW

**Comment by craigmacgregor** [comment]
I'm getting a 404 on the project page when i click "read more" from the item on /projects

https://navhub.org/projects/navcoin-mate/

**Comment by craigmacgregor** [comment]
ah, i see, i need to look at: https://deploy-preview-60--compassionate-colden-815a55.netlify.com/projects/navcoin-mate/

**Comment by craigmacgregor** [comment]
looks good. I would suggest that any icons on a blue horizontal slice should have the dark blue backgrounds rather than the dark purple. All the icons should have blue and purple variants in the zip found in the branding guidelines: http://bit.ly/iconpack-05-2018

Either way it's up to you how you want this page to look, this is just a recommendation for consistency around how we've done the rest of the pages.

**Comment by IfaqYurmama** [comment]
@zanuka that's cause the project page doesnt exist yet, when this is merged it will be available under that link

**Comment by IfaqYurmama** [comment]
@craigmacgregor I'll update the icons today

**Comment by zanuka** [comment]
@IfaqYurmama ok, my bad...  I thought it would preview the page using relative links from the netlify build like we're doing in the new pr for the how to guide. makes sense, will re-approve.

**Comment by IfaqYurmama** [comment]
@craigmacgregor I changed the icons

**Comment by zanuka** [comment]
@IfaqYurmama still seems like we should be able to preview this page w/ local url. i've been able to do that with other sections of the site

**Comment by IfaqYurmama** [comment]
done @craigmacgregor

**Pull request merged**
